language: ruby

rvm:
  - 1.9.3

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - rake app:db:create
  - rake app:db:migrate
  - rake app:db:test:prepare

after_script:
  - rake app:db:rollback